name: Docker Image CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Delete old images
      run: docker image prune --force
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ebal5/nlp-apps:$(date +%s)
